### ISSUE TITLE
Results interpretation

### ISSUE THREAD

**Issue by ricardovialle** [wesleycrouse/bmediatR#2]
Dear Wesley,
I having trouble interpreting the output results, I'm wondering if you can help me.
For example, I'm looking the mediation of Protein QTL (outcome) via RNA QTL (mediator). Here is part of the output table.

```
ID                 mediation    partial   complete    colocal mediation_or_colocal y_depends_x reactive y_depends_m outcome
ENSG00000106771.12 10.287129 -1.0623030  1.0621245 -12.907885            10.362663   10.659415     -Inf   12.902179 TMEM245
ENSG00000141560.14 10.070827 -1.3440731  1.3438153 -11.387707            10.382784   10.612949     -Inf   11.371091  FN3KRP
ENSG00000116791.13  9.883795 -0.9219875  0.9217371 -19.405890             9.883868   10.218751     -Inf   19.404426    CRYZ
ENSG00000134201.10  7.532775  1.7794634 -1.7838008  -9.085619             7.770809    9.709473     -Inf    9.084967   GSTM5
ENSG00000100304.12  6.382313  1.3598483 -1.3702676  -6.434055             9.372758   10.939185     -Inf    6.433557  TTLL12
ENSG00000215845.10  5.968219 -1.9898934  1.9659886  -7.554481             6.198290    6.301313     -Inf    6.995380   TSTD1
```

Which columns should I use to say that RNA is mediating to Protein. Do you suggest some threshold cut to choose between mediation and colocal, or there is no such thing?

Thanks!

**Comment by wesleycrouse** [comment]
Hi Ricardo,

Thanks for reaching out, glad you are using the software. These are log posterior odds in favor of different relationships between the outcome, independent variable, and mediator. The "mediation" column is the posterior odds of either complete or partial mediation and is the column you are probably interested in. You can compare these posterior odds with the "ln_prior_odds" in the output to get a sense for how far the data has moved the prior. Assuming you used a uniform prior (the default), it looks like all of these show evidence in favor of mediation (posterior odds bigger than prior odds).

There isn't really a threshold for significance _per se_ since this a Bayesian procedure. It may be helpful to think about these results by considering a posterior probability threshold that you want to define and converting to log odds using ln(p/(1-p)). For example: 50% posterior probability of mediation = 0 log odds; 95% probability ≈ 2.94 log odds; 99% probability ≈ 4.59 log odds. So your results all look pretty decisively like mediation. You can also look at the results on the (ln) probability scale directly using "ln_post_c" in the output... exponentiate them and sum the "1,1,0" (complete mediation) and "1,1,1" (partial mediation) cases to get a posterior probability of either partial or complete mediation.

If you are comparing different candidate mediators, it may also be useful to plot the posterior odds by genomic position of the mediator to see if there's a clear peak for mediation and some of the other candidates are tagging along.

Hope that helps. Feel free to ask additional questions or make suggestions regarding the output. We are still in the process of figuring out how best to present these results, and we plan to make a vignette in the near future.

-Wes

**Comment by ricardovialle** [comment]
Hi Wes, thanks a lot! 
That was really helpful, I'll try your suggestions.

Thanks!
